FROM ubuntu:14.04

# Update the repository sources list
RUN apt-get update

# Install Git
RUN apt-get install -y git

# Install PHP5 & Nginx
RUN apt-get install -y php5-common php5-fpm php5-cli nginx

#Remove files if exists
RUN if test -d /usr/share/nginx/html/happy-family-php/config; then rm -R /usr/share/nginx/html/happy-family-php/config; fi 

WORKDIR /usr/share/nginx/html

#Git Clone Repo
RUN git clone https://github.com/darylvisenze/happy-family-php.git

#Nginx Config
RUN cp /usr/share/nginx/html/happy-family-php/config/nginx-conf /etc/nginx/sites-available/default
