FROM ubuntu:14.04

# Update the repository sources list
RUN apt-get update

# Install Git
RUN apt-get install -y git

# Install PHP5
RUN apt-get install -y php5-common php5-fpm php5-cli

#nginx
RUN apt-get install -y nginx

#Remove files if exists
RUN if test -d /usr/share/nginx/html/happy-family-php/config; then rm -R /usr/share/nginx/html/happy-family-php/config; fi 

WORKDIR /usr/share/nginx/html

#Git Clone Repo
RUN git clone https://github.com/darylvisenze/happy-family-php.git

#Start Services
RUN service php5-fpm start
RUN service nginx start
